# This workflow will do a clean install of node dependencies, build the source code and run tests and linters across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Build Status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Install Dependencies
      run: npm i
    - name: Run a test build
      run: npm run build
    - name: Run Lint Checks
      run: npm run lint
    - name: Run Test 
      run: npm test:ci
    - uses: ziishaned/jest-reporter-action@v0.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: "npm run test:coverage"
